allspark: Updated Spark dependencies (PYSPARK_SUBMIT_ARGS)
also removed duplication of `PYSPARK_SUBMIT_ARGS` which was set
twice both in the `Dockerfile` and in the `pyspark-s3.py` script.

Why?
----
Robin L. testing found an issue related to S3:

```
Py4JJavaError: An error occurred while calling o103.parquet.
: java.lang.NumberFormatException: For input string: "100M"
[...]
```

[SO Question] leads to an [`hadoop-common` issue] which seems to
be resolved in a more recent version.

I've updated versions in `PYSPARK_SUBMIT_ARGS` environment variable
hoping these newer versions work without problems. But we may need to
tweak this further to make things work.

[SO Question]: https://stackoverflow.com/questions/60172792/reading-data-from-s3-using-pyspark-throws-java-lang-numberformatexception-for-i
[`hadoop-common` issue]: https://issues.apache.org/jira/browse/HADOOP-13680