allspark: Install DE packages from pypi
Also removed now archived/unused `dataengineeringutils`
package.

This is to fix weird error when installing from GH:

```
ERROR: Requested unknown from git+https://github.com/moj-analytical-services/gluejobutils/#egg=gluejobutils has different name in metadata: 'UNKNOWN'
```

See discussion with DE team: https://mojdt.slack.com/archives/CBVUV2613/p1607013099088400